---
repos:
  - repo: local
    hooks:
      - id: run-unittests
        name: Run unittests
        entry: env PYTHONPATH=src/compilation python -m unittest discover -s tests
        language: system
        pass_filenames: false

  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
#        args: [ "--check" ]  # Only checks, doesn't format

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # against error
    hooks:
      - id: isort
        args: [ "--profile", "black" ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: '.*\.pth$'
      - id: debug-statements
